[2025-03-15T06:33:54.538+0000] {processor.py:186} INFO - Started process (PID=69) to work on /opt/airflow/dags/A0265912B.py
[2025-03-15T06:33:54.538+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-15T06:33:54.539+0000] {logging_mixin.py:190} INFO - [2025-03-15T06:33:54.539+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-15T06:33:54.548+0000] {logging_mixin.py:190} INFO - [2025-03-15T06:33:54.545+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-15T06:33:54.548+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-15T06:33:54.557+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.021 seconds
[2025-03-15T06:34:24.907+0000] {processor.py:186} INFO - Started process (PID=135) to work on /opt/airflow/dags/A0265912B.py
[2025-03-15T06:34:24.908+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-15T06:34:24.910+0000] {logging_mixin.py:190} INFO - [2025-03-15T06:34:24.910+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-15T06:34:24.917+0000] {logging_mixin.py:190} INFO - [2025-03-15T06:34:24.915+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-15T06:34:24.917+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-15T06:34:24.934+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.029 seconds
[2025-03-15T06:34:55.326+0000] {processor.py:186} INFO - Started process (PID=200) to work on /opt/airflow/dags/A0265912B.py
[2025-03-15T06:34:55.326+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-15T06:34:55.327+0000] {logging_mixin.py:190} INFO - [2025-03-15T06:34:55.327+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-15T06:34:55.337+0000] {logging_mixin.py:190} INFO - [2025-03-15T06:34:55.333+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-15T06:34:55.337+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-15T06:34:55.348+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.024 seconds
[2025-03-15T06:35:26.071+0000] {processor.py:186} INFO - Started process (PID=265) to work on /opt/airflow/dags/A0265912B.py
[2025-03-15T06:35:26.072+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-15T06:35:26.074+0000] {logging_mixin.py:190} INFO - [2025-03-15T06:35:26.073+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-15T06:35:26.083+0000] {logging_mixin.py:190} INFO - [2025-03-15T06:35:26.078+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-15T06:35:26.084+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-15T06:35:26.093+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.024 seconds
[2025-03-15T06:35:56.639+0000] {processor.py:186} INFO - Started process (PID=331) to work on /opt/airflow/dags/A0265912B.py
[2025-03-15T06:35:56.639+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-15T06:35:56.642+0000] {logging_mixin.py:190} INFO - [2025-03-15T06:35:56.641+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-15T06:35:56.649+0000] {logging_mixin.py:190} INFO - [2025-03-15T06:35:56.645+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-15T06:35:56.649+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-15T06:35:56.658+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.021 seconds
[2025-03-15T06:36:27.039+0000] {processor.py:186} INFO - Started process (PID=397) to work on /opt/airflow/dags/A0265912B.py
[2025-03-15T06:36:27.040+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-15T06:36:27.041+0000] {logging_mixin.py:190} INFO - [2025-03-15T06:36:27.041+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-15T06:36:27.051+0000] {logging_mixin.py:190} INFO - [2025-03-15T06:36:27.051+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-15T06:36:27.052+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-15T06:36:27.060+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.024 seconds
[2025-03-15T06:36:57.438+0000] {processor.py:186} INFO - Started process (PID=462) to work on /opt/airflow/dags/A0265912B.py
[2025-03-15T06:36:57.438+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-15T06:36:57.440+0000] {logging_mixin.py:190} INFO - [2025-03-15T06:36:57.440+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-15T06:36:57.447+0000] {logging_mixin.py:190} INFO - [2025-03-15T06:36:57.443+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-15T06:36:57.447+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-15T06:36:57.456+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.020 seconds
[2025-03-15T06:37:27.714+0000] {processor.py:186} INFO - Started process (PID=528) to work on /opt/airflow/dags/A0265912B.py
[2025-03-15T06:37:27.714+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-15T06:37:27.715+0000] {logging_mixin.py:190} INFO - [2025-03-15T06:37:27.715+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-15T06:37:27.720+0000] {logging_mixin.py:190} INFO - [2025-03-15T06:37:27.720+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-15T06:37:27.721+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-15T06:37:27.731+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.020 seconds
[2025-03-15T06:37:57.975+0000] {processor.py:186} INFO - Started process (PID=594) to work on /opt/airflow/dags/A0265912B.py
[2025-03-15T06:37:57.975+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-15T06:37:57.976+0000] {logging_mixin.py:190} INFO - [2025-03-15T06:37:57.976+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-15T06:37:57.984+0000] {logging_mixin.py:190} INFO - [2025-03-15T06:37:57.983+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-15T06:37:57.985+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-15T06:37:57.996+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.024 seconds
[2025-03-15T06:38:28.173+0000] {processor.py:186} INFO - Started process (PID=660) to work on /opt/airflow/dags/A0265912B.py
[2025-03-15T06:38:28.173+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-15T06:38:28.174+0000] {logging_mixin.py:190} INFO - [2025-03-15T06:38:28.174+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-15T06:38:28.181+0000] {logging_mixin.py:190} INFO - [2025-03-15T06:38:28.180+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-15T06:38:28.183+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-15T06:38:28.195+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.024 seconds
[2025-03-15T06:38:58.326+0000] {processor.py:186} INFO - Started process (PID=725) to work on /opt/airflow/dags/A0265912B.py
[2025-03-15T06:38:58.327+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-15T06:38:58.328+0000] {logging_mixin.py:190} INFO - [2025-03-15T06:38:58.328+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-15T06:38:58.336+0000] {logging_mixin.py:190} INFO - [2025-03-15T06:38:58.335+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-15T06:38:58.336+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-15T06:38:58.347+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.023 seconds
[2025-03-15T06:39:28.557+0000] {processor.py:186} INFO - Started process (PID=798) to work on /opt/airflow/dags/A0265912B.py
[2025-03-15T06:39:28.557+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-15T06:39:28.559+0000] {logging_mixin.py:190} INFO - [2025-03-15T06:39:28.558+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-15T06:39:28.566+0000] {logging_mixin.py:190} INFO - [2025-03-15T06:39:28.563+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-15T06:39:28.568+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-15T06:39:28.582+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.027 seconds
[2025-03-15T06:39:58.835+0000] {processor.py:186} INFO - Started process (PID=864) to work on /opt/airflow/dags/A0265912B.py
[2025-03-15T06:39:58.836+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-15T06:39:58.837+0000] {logging_mixin.py:190} INFO - [2025-03-15T06:39:58.837+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-15T06:39:58.844+0000] {logging_mixin.py:190} INFO - [2025-03-15T06:39:58.840+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-15T06:39:58.844+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-15T06:39:58.854+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.021 seconds
[2025-03-15T06:40:29.090+0000] {processor.py:186} INFO - Started process (PID=930) to work on /opt/airflow/dags/A0265912B.py
[2025-03-15T06:40:29.091+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-15T06:40:29.092+0000] {logging_mixin.py:190} INFO - [2025-03-15T06:40:29.092+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-15T06:40:29.098+0000] {logging_mixin.py:190} INFO - [2025-03-15T06:40:29.097+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-15T06:40:29.098+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-15T06:40:29.107+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.019 seconds
[2025-03-15T06:40:59.310+0000] {processor.py:186} INFO - Started process (PID=996) to work on /opt/airflow/dags/A0265912B.py
[2025-03-15T06:40:59.310+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-15T06:40:59.311+0000] {logging_mixin.py:190} INFO - [2025-03-15T06:40:59.311+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-15T06:40:59.318+0000] {logging_mixin.py:190} INFO - [2025-03-15T06:40:59.314+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-15T06:40:59.319+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-15T06:40:59.329+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.021 seconds
[2025-03-15T06:41:29.637+0000] {processor.py:186} INFO - Started process (PID=1062) to work on /opt/airflow/dags/A0265912B.py
[2025-03-15T06:41:29.638+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-15T06:41:29.639+0000] {logging_mixin.py:190} INFO - [2025-03-15T06:41:29.639+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-15T06:41:29.649+0000] {logging_mixin.py:190} INFO - [2025-03-15T06:41:29.643+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-15T06:41:29.652+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-15T06:41:29.661+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.025 seconds
[2025-03-15T06:42:00.141+0000] {processor.py:186} INFO - Started process (PID=1127) to work on /opt/airflow/dags/A0265912B.py
[2025-03-15T06:42:00.142+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-15T06:42:00.143+0000] {logging_mixin.py:190} INFO - [2025-03-15T06:42:00.143+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-15T06:42:00.150+0000] {logging_mixin.py:190} INFO - [2025-03-15T06:42:00.149+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-15T06:42:00.150+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-15T06:42:00.160+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.021 seconds
[2025-03-15T06:42:30.607+0000] {processor.py:186} INFO - Started process (PID=1193) to work on /opt/airflow/dags/A0265912B.py
[2025-03-15T06:42:30.607+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-15T06:42:30.608+0000] {logging_mixin.py:190} INFO - [2025-03-15T06:42:30.608+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-15T06:42:30.615+0000] {logging_mixin.py:190} INFO - [2025-03-15T06:42:30.611+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-15T06:42:30.618+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-15T06:42:30.633+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.028 seconds
[2025-03-15T06:43:00.927+0000] {processor.py:186} INFO - Started process (PID=1259) to work on /opt/airflow/dags/A0265912B.py
[2025-03-15T06:43:00.927+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-15T06:43:00.928+0000] {logging_mixin.py:190} INFO - [2025-03-15T06:43:00.928+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-15T06:43:00.936+0000] {logging_mixin.py:190} INFO - [2025-03-15T06:43:00.935+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-15T06:43:00.936+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-15T06:43:00.944+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.020 seconds
[2025-03-15T06:43:31.280+0000] {processor.py:186} INFO - Started process (PID=1325) to work on /opt/airflow/dags/A0265912B.py
[2025-03-15T06:43:31.280+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-15T06:43:31.282+0000] {logging_mixin.py:190} INFO - [2025-03-15T06:43:31.282+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-15T06:43:31.289+0000] {logging_mixin.py:190} INFO - [2025-03-15T06:43:31.285+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-15T06:43:31.290+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-15T06:43:31.300+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.022 seconds
[2025-03-15T06:44:01.521+0000] {processor.py:186} INFO - Started process (PID=1390) to work on /opt/airflow/dags/A0265912B.py
[2025-03-15T06:44:01.522+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-15T06:44:01.523+0000] {logging_mixin.py:190} INFO - [2025-03-15T06:44:01.523+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-15T06:44:01.531+0000] {logging_mixin.py:190} INFO - [2025-03-15T06:44:01.530+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-15T06:44:01.531+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-15T06:44:01.542+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.024 seconds
[2025-03-15T06:44:31.740+0000] {processor.py:186} INFO - Started process (PID=1456) to work on /opt/airflow/dags/A0265912B.py
[2025-03-15T06:44:31.741+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-15T06:44:31.742+0000] {logging_mixin.py:190} INFO - [2025-03-15T06:44:31.742+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-15T06:44:31.746+0000] {logging_mixin.py:190} INFO - [2025-03-15T06:44:31.746+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-15T06:44:31.747+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-15T06:44:31.758+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.020 seconds
[2025-03-15T06:45:02.081+0000] {processor.py:186} INFO - Started process (PID=1522) to work on /opt/airflow/dags/A0265912B.py
[2025-03-15T06:45:02.082+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-15T06:45:02.083+0000] {logging_mixin.py:190} INFO - [2025-03-15T06:45:02.083+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-15T06:45:02.093+0000] {logging_mixin.py:190} INFO - [2025-03-15T06:45:02.091+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-15T06:45:02.093+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-15T06:45:02.104+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.025 seconds
[2025-03-15T06:45:32.484+0000] {processor.py:186} INFO - Started process (PID=1588) to work on /opt/airflow/dags/A0265912B.py
[2025-03-15T06:45:32.484+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-15T06:45:32.485+0000] {logging_mixin.py:190} INFO - [2025-03-15T06:45:32.485+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-15T06:45:32.489+0000] {logging_mixin.py:190} INFO - [2025-03-15T06:45:32.488+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-15T06:45:32.491+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-15T06:45:32.502+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.021 seconds
[2025-03-15T06:46:02.957+0000] {processor.py:186} INFO - Started process (PID=1654) to work on /opt/airflow/dags/A0265912B.py
[2025-03-15T06:46:02.957+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-15T06:46:02.958+0000] {logging_mixin.py:190} INFO - [2025-03-15T06:46:02.958+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-15T06:46:02.965+0000] {logging_mixin.py:190} INFO - [2025-03-15T06:46:02.964+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-15T06:46:02.965+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-15T06:46:02.974+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.020 seconds
[2025-03-15T06:46:33.347+0000] {processor.py:186} INFO - Started process (PID=1720) to work on /opt/airflow/dags/A0265912B.py
[2025-03-15T06:46:33.348+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-15T06:46:33.349+0000] {logging_mixin.py:190} INFO - [2025-03-15T06:46:33.349+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-15T06:46:33.352+0000] {logging_mixin.py:190} INFO - [2025-03-15T06:46:33.351+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-15T06:46:33.353+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-15T06:46:33.363+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.018 seconds
[2025-03-15T06:47:03.826+0000] {processor.py:186} INFO - Started process (PID=1786) to work on /opt/airflow/dags/A0265912B.py
[2025-03-15T06:47:03.827+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-15T06:47:03.828+0000] {logging_mixin.py:190} INFO - [2025-03-15T06:47:03.828+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-15T06:47:03.834+0000] {logging_mixin.py:190} INFO - [2025-03-15T06:47:03.831+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-15T06:47:03.834+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-15T06:47:03.845+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.021 seconds
[2025-03-15T06:47:34.275+0000] {processor.py:186} INFO - Started process (PID=1852) to work on /opt/airflow/dags/A0265912B.py
[2025-03-15T06:47:34.276+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-15T06:47:34.277+0000] {logging_mixin.py:190} INFO - [2025-03-15T06:47:34.277+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-15T06:47:34.283+0000] {logging_mixin.py:190} INFO - [2025-03-15T06:47:34.280+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-15T06:47:34.284+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-15T06:47:34.295+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.022 seconds
[2025-03-15T06:48:04.669+0000] {processor.py:186} INFO - Started process (PID=1918) to work on /opt/airflow/dags/A0265912B.py
[2025-03-15T06:48:04.669+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-15T06:48:04.670+0000] {logging_mixin.py:190} INFO - [2025-03-15T06:48:04.670+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-15T06:48:04.674+0000] {logging_mixin.py:190} INFO - [2025-03-15T06:48:04.672+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-15T06:48:04.674+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-15T06:48:04.686+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.020 seconds
[2025-03-15T06:48:35.055+0000] {processor.py:186} INFO - Started process (PID=1984) to work on /opt/airflow/dags/A0265912B.py
[2025-03-15T06:48:35.055+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-15T06:48:35.056+0000] {logging_mixin.py:190} INFO - [2025-03-15T06:48:35.056+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-15T06:48:35.064+0000] {logging_mixin.py:190} INFO - [2025-03-15T06:48:35.061+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-15T06:48:35.064+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-15T06:48:35.074+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.022 seconds
[2025-03-15T06:49:05.660+0000] {processor.py:186} INFO - Started process (PID=2050) to work on /opt/airflow/dags/A0265912B.py
[2025-03-15T06:49:05.660+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-15T06:49:05.661+0000] {logging_mixin.py:190} INFO - [2025-03-15T06:49:05.661+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-15T06:49:05.669+0000] {logging_mixin.py:190} INFO - [2025-03-15T06:49:05.668+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-15T06:49:05.669+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-15T06:49:05.682+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.025 seconds
[2025-03-15T06:49:36.116+0000] {processor.py:186} INFO - Started process (PID=2116) to work on /opt/airflow/dags/A0265912B.py
[2025-03-15T06:49:36.116+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-15T06:49:36.117+0000] {logging_mixin.py:190} INFO - [2025-03-15T06:49:36.117+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-15T06:49:36.125+0000] {logging_mixin.py:190} INFO - [2025-03-15T06:49:36.121+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-15T06:49:36.125+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-15T06:49:36.137+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.024 seconds
[2025-03-15T06:50:06.435+0000] {processor.py:186} INFO - Started process (PID=2182) to work on /opt/airflow/dags/A0265912B.py
[2025-03-15T06:50:06.435+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-15T06:50:06.436+0000] {logging_mixin.py:190} INFO - [2025-03-15T06:50:06.436+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-15T06:50:06.443+0000] {logging_mixin.py:190} INFO - [2025-03-15T06:50:06.439+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-15T06:50:06.443+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-15T06:50:06.453+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.021 seconds
[2025-03-15T06:50:36.831+0000] {processor.py:186} INFO - Started process (PID=2248) to work on /opt/airflow/dags/A0265912B.py
[2025-03-15T06:50:36.832+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-15T06:50:36.834+0000] {logging_mixin.py:190} INFO - [2025-03-15T06:50:36.833+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-15T06:50:36.840+0000] {logging_mixin.py:190} INFO - [2025-03-15T06:50:36.839+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-15T06:50:36.841+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-15T06:50:36.850+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.022 seconds
[2025-03-15T06:51:07.240+0000] {processor.py:186} INFO - Started process (PID=2314) to work on /opt/airflow/dags/A0265912B.py
[2025-03-15T06:51:07.241+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-15T06:51:07.242+0000] {logging_mixin.py:190} INFO - [2025-03-15T06:51:07.242+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-15T06:51:07.249+0000] {logging_mixin.py:190} INFO - [2025-03-15T06:51:07.246+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-15T06:51:07.249+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-15T06:51:07.262+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.025 seconds
[2025-03-15T06:51:37.653+0000] {processor.py:186} INFO - Started process (PID=2380) to work on /opt/airflow/dags/A0265912B.py
[2025-03-15T06:51:37.653+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-15T06:51:37.654+0000] {logging_mixin.py:190} INFO - [2025-03-15T06:51:37.654+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-15T06:51:37.661+0000] {logging_mixin.py:190} INFO - [2025-03-15T06:51:37.657+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-15T06:51:37.661+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-15T06:51:37.673+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.023 seconds
[2025-03-15T06:52:08.045+0000] {processor.py:186} INFO - Started process (PID=2445) to work on /opt/airflow/dags/A0265912B.py
[2025-03-15T06:52:08.046+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-15T06:52:08.047+0000] {logging_mixin.py:190} INFO - [2025-03-15T06:52:08.047+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-15T06:52:08.054+0000] {logging_mixin.py:190} INFO - [2025-03-15T06:52:08.052+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-15T06:52:08.054+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-15T06:52:08.068+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.025 seconds
[2025-03-15T06:52:38.558+0000] {processor.py:186} INFO - Started process (PID=2511) to work on /opt/airflow/dags/A0265912B.py
[2025-03-15T06:52:38.558+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-15T06:52:38.559+0000] {logging_mixin.py:190} INFO - [2025-03-15T06:52:38.559+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-15T06:52:38.566+0000] {logging_mixin.py:190} INFO - [2025-03-15T06:52:38.564+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-15T06:52:38.567+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-15T06:52:38.576+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.020 seconds
[2025-03-15T06:53:09.177+0000] {processor.py:186} INFO - Started process (PID=2577) to work on /opt/airflow/dags/A0265912B.py
[2025-03-15T06:53:09.177+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-15T06:53:09.179+0000] {logging_mixin.py:190} INFO - [2025-03-15T06:53:09.179+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-15T06:53:09.186+0000] {logging_mixin.py:190} INFO - [2025-03-15T06:53:09.185+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-15T06:53:09.186+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-15T06:53:09.201+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.026 seconds
[2025-03-15T06:53:39.464+0000] {processor.py:186} INFO - Started process (PID=2643) to work on /opt/airflow/dags/A0265912B.py
[2025-03-15T06:53:39.464+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-15T06:53:39.465+0000] {logging_mixin.py:190} INFO - [2025-03-15T06:53:39.465+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-15T06:53:39.472+0000] {logging_mixin.py:190} INFO - [2025-03-15T06:53:39.470+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-15T06:53:39.473+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-15T06:53:39.483+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.022 seconds
[2025-03-15T06:54:09.963+0000] {processor.py:186} INFO - Started process (PID=2709) to work on /opt/airflow/dags/A0265912B.py
[2025-03-15T06:54:09.964+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-15T06:54:09.965+0000] {logging_mixin.py:190} INFO - [2025-03-15T06:54:09.965+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-15T06:54:09.972+0000] {logging_mixin.py:190} INFO - [2025-03-15T06:54:09.972+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-15T06:54:09.973+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-15T06:54:09.982+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.021 seconds
[2025-03-15T06:54:40.156+0000] {processor.py:186} INFO - Started process (PID=2775) to work on /opt/airflow/dags/A0265912B.py
[2025-03-15T06:54:40.156+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-15T06:54:40.158+0000] {logging_mixin.py:190} INFO - [2025-03-15T06:54:40.158+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-15T06:54:40.167+0000] {logging_mixin.py:190} INFO - [2025-03-15T06:54:40.165+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-15T06:54:40.167+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-15T06:54:40.269+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.115 seconds
[2025-03-15T06:55:10.736+0000] {processor.py:186} INFO - Started process (PID=2841) to work on /opt/airflow/dags/A0265912B.py
[2025-03-15T06:55:10.736+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-15T06:55:10.738+0000] {logging_mixin.py:190} INFO - [2025-03-15T06:55:10.737+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-15T06:55:10.745+0000] {logging_mixin.py:190} INFO - [2025-03-15T06:55:10.742+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-15T06:55:10.746+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-15T06:55:10.757+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.024 seconds
[2025-03-15T06:55:40.930+0000] {processor.py:186} INFO - Started process (PID=2907) to work on /opt/airflow/dags/A0265912B.py
[2025-03-15T06:55:40.930+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-15T06:55:40.931+0000] {logging_mixin.py:190} INFO - [2025-03-15T06:55:40.931+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-15T06:55:40.934+0000] {logging_mixin.py:190} INFO - [2025-03-15T06:55:40.934+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-15T06:55:40.935+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-15T06:55:40.947+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.020 seconds
[2025-03-15T06:56:11.108+0000] {processor.py:186} INFO - Started process (PID=2972) to work on /opt/airflow/dags/A0265912B.py
[2025-03-15T06:56:11.109+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-15T06:56:11.110+0000] {logging_mixin.py:190} INFO - [2025-03-15T06:56:11.110+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-15T06:56:11.116+0000] {logging_mixin.py:190} INFO - [2025-03-15T06:56:11.113+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-15T06:56:11.116+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-15T06:56:11.127+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.021 seconds
[2025-03-15T06:56:41.267+0000] {processor.py:186} INFO - Started process (PID=3038) to work on /opt/airflow/dags/A0265912B.py
[2025-03-15T06:56:41.268+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-15T06:56:41.270+0000] {logging_mixin.py:190} INFO - [2025-03-15T06:56:41.269+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-15T06:56:41.277+0000] {logging_mixin.py:190} INFO - [2025-03-15T06:56:41.274+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-15T06:56:41.277+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-15T06:56:41.291+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.027 seconds
[2025-03-15T06:57:11.447+0000] {processor.py:186} INFO - Started process (PID=3104) to work on /opt/airflow/dags/A0265912B.py
[2025-03-15T06:57:11.448+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-15T06:57:11.449+0000] {logging_mixin.py:190} INFO - [2025-03-15T06:57:11.449+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-15T06:57:11.456+0000] {logging_mixin.py:190} INFO - [2025-03-15T06:57:11.453+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-15T06:57:11.457+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-15T06:57:11.466+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.022 seconds
[2025-03-15T06:57:41.680+0000] {processor.py:186} INFO - Started process (PID=3170) to work on /opt/airflow/dags/A0265912B.py
[2025-03-15T06:57:41.680+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-15T06:57:41.682+0000] {logging_mixin.py:190} INFO - [2025-03-15T06:57:41.682+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-15T06:57:41.687+0000] {logging_mixin.py:190} INFO - [2025-03-15T06:57:41.685+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-15T06:57:41.688+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-15T06:57:41.699+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.022 seconds
[2025-03-15T06:58:11.939+0000] {processor.py:186} INFO - Started process (PID=3236) to work on /opt/airflow/dags/A0265912B.py
[2025-03-15T06:58:11.939+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-15T06:58:11.940+0000] {logging_mixin.py:190} INFO - [2025-03-15T06:58:11.940+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-15T06:58:11.948+0000] {logging_mixin.py:190} INFO - [2025-03-15T06:58:11.945+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-15T06:58:11.948+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-15T06:58:11.958+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.022 seconds
[2025-03-15T06:58:42.162+0000] {processor.py:186} INFO - Started process (PID=3302) to work on /opt/airflow/dags/A0265912B.py
[2025-03-15T06:58:42.163+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-15T06:58:42.164+0000] {logging_mixin.py:190} INFO - [2025-03-15T06:58:42.164+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-15T06:58:42.168+0000] {logging_mixin.py:190} INFO - [2025-03-15T06:58:42.167+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-15T06:58:42.168+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-15T06:58:42.179+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.020 seconds
[2025-03-15T06:59:13.185+0000] {processor.py:186} INFO - Started process (PID=3369) to work on /opt/airflow/dags/A0265912B.py
[2025-03-15T06:59:13.185+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-15T06:59:13.187+0000] {logging_mixin.py:190} INFO - [2025-03-15T06:59:13.187+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-15T06:59:13.193+0000] {logging_mixin.py:190} INFO - [2025-03-15T06:59:13.193+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-15T06:59:13.194+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-15T06:59:13.205+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.023 seconds
[2025-03-15T06:59:43.365+0000] {processor.py:186} INFO - Started process (PID=3434) to work on /opt/airflow/dags/A0265912B.py
[2025-03-15T06:59:43.365+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-15T06:59:43.367+0000] {logging_mixin.py:190} INFO - [2025-03-15T06:59:43.367+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-15T06:59:43.373+0000] {logging_mixin.py:190} INFO - [2025-03-15T06:59:43.372+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-15T06:59:43.373+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-15T06:59:43.385+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.023 seconds
[2025-03-15T07:00:13.937+0000] {processor.py:186} INFO - Started process (PID=3499) to work on /opt/airflow/dags/A0265912B.py
[2025-03-15T07:00:13.938+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-15T07:00:13.940+0000] {logging_mixin.py:190} INFO - [2025-03-15T07:00:13.939+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-15T07:00:13.943+0000] {logging_mixin.py:190} INFO - [2025-03-15T07:00:13.942+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-15T07:00:13.943+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-15T07:00:13.953+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.017 seconds
[2025-03-15T07:00:44.133+0000] {processor.py:186} INFO - Started process (PID=3565) to work on /opt/airflow/dags/A0265912B.py
[2025-03-15T07:00:44.133+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-15T07:00:44.135+0000] {logging_mixin.py:190} INFO - [2025-03-15T07:00:44.135+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-15T07:00:44.148+0000] {logging_mixin.py:190} INFO - [2025-03-15T07:00:44.138+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-15T07:00:44.149+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-15T07:00:44.157+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.027 seconds
[2025-03-15T07:01:14.924+0000] {processor.py:186} INFO - Started process (PID=3631) to work on /opt/airflow/dags/A0265912B.py
[2025-03-15T07:01:14.925+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-15T07:01:14.926+0000] {logging_mixin.py:190} INFO - [2025-03-15T07:01:14.926+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-15T07:01:14.933+0000] {logging_mixin.py:190} INFO - [2025-03-15T07:01:14.932+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-15T07:01:14.933+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-15T07:01:14.946+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.024 seconds
[2025-03-15T07:01:45.505+0000] {processor.py:186} INFO - Started process (PID=3697) to work on /opt/airflow/dags/A0265912B.py
[2025-03-15T07:01:45.506+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-15T07:01:45.507+0000] {logging_mixin.py:190} INFO - [2025-03-15T07:01:45.507+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-15T07:01:45.514+0000] {logging_mixin.py:190} INFO - [2025-03-15T07:01:45.513+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-15T07:01:45.514+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-15T07:01:45.527+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.025 seconds
[2025-03-15T07:02:15.830+0000] {processor.py:186} INFO - Started process (PID=3763) to work on /opt/airflow/dags/A0265912B.py
[2025-03-15T07:02:15.830+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-15T07:02:15.832+0000] {logging_mixin.py:190} INFO - [2025-03-15T07:02:15.832+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-15T07:02:15.841+0000] {logging_mixin.py:190} INFO - [2025-03-15T07:02:15.841+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-15T07:02:15.842+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-15T07:02:15.855+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.028 seconds
[2025-03-15T07:02:46.448+0000] {processor.py:186} INFO - Started process (PID=3829) to work on /opt/airflow/dags/A0265912B.py
[2025-03-15T07:02:46.448+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-15T07:02:46.450+0000] {logging_mixin.py:190} INFO - [2025-03-15T07:02:46.450+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-15T07:02:46.457+0000] {logging_mixin.py:190} INFO - [2025-03-15T07:02:46.456+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-15T07:02:46.457+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-15T07:02:46.465+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.019 seconds
[2025-03-15T07:03:16.860+0000] {processor.py:186} INFO - Started process (PID=3895) to work on /opt/airflow/dags/A0265912B.py
[2025-03-15T07:03:16.861+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-15T07:03:16.862+0000] {logging_mixin.py:190} INFO - [2025-03-15T07:03:16.862+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-15T07:03:16.871+0000] {logging_mixin.py:190} INFO - [2025-03-15T07:03:16.867+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-15T07:03:16.872+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-15T07:03:16.883+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.026 seconds
[2025-03-15T07:03:47.298+0000] {processor.py:186} INFO - Started process (PID=3960) to work on /opt/airflow/dags/A0265912B.py
[2025-03-15T07:03:47.299+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-15T07:03:47.301+0000] {logging_mixin.py:190} INFO - [2025-03-15T07:03:47.301+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-15T07:03:47.312+0000] {logging_mixin.py:190} INFO - [2025-03-15T07:03:47.305+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-15T07:03:47.312+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-15T07:03:47.321+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.025 seconds
[2025-03-15T07:04:17.694+0000] {processor.py:186} INFO - Started process (PID=4025) to work on /opt/airflow/dags/A0265912B.py
[2025-03-15T07:04:17.695+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-15T07:04:17.697+0000] {logging_mixin.py:190} INFO - [2025-03-15T07:04:17.697+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-15T07:04:17.717+0000] {logging_mixin.py:190} INFO - [2025-03-15T07:04:17.716+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-15T07:04:17.718+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-15T07:04:17.730+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.038 seconds
[2025-03-15T07:04:48.484+0000] {processor.py:186} INFO - Started process (PID=4091) to work on /opt/airflow/dags/A0265912B.py
[2025-03-15T07:04:48.485+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-15T07:04:48.486+0000] {logging_mixin.py:190} INFO - [2025-03-15T07:04:48.486+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-15T07:04:48.494+0000] {logging_mixin.py:190} INFO - [2025-03-15T07:04:48.493+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-15T07:04:48.494+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-15T07:04:48.504+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.022 seconds
[2025-03-15T07:05:18.761+0000] {processor.py:186} INFO - Started process (PID=4157) to work on /opt/airflow/dags/A0265912B.py
[2025-03-15T07:05:18.761+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-15T07:05:18.763+0000] {logging_mixin.py:190} INFO - [2025-03-15T07:05:18.763+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-15T07:05:18.776+0000] {logging_mixin.py:190} INFO - [2025-03-15T07:05:18.775+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-15T07:05:18.776+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-15T07:05:18.785+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.027 seconds
[2025-03-15T07:05:49.536+0000] {processor.py:186} INFO - Started process (PID=4223) to work on /opt/airflow/dags/A0265912B.py
[2025-03-15T07:05:49.537+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-15T07:05:49.538+0000] {logging_mixin.py:190} INFO - [2025-03-15T07:05:49.538+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-15T07:05:49.542+0000] {logging_mixin.py:190} INFO - [2025-03-15T07:05:49.541+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-15T07:05:49.542+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-15T07:05:49.551+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.017 seconds
[2025-03-15T07:06:19.853+0000] {processor.py:186} INFO - Started process (PID=4289) to work on /opt/airflow/dags/A0265912B.py
[2025-03-15T07:06:19.853+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-15T07:06:19.855+0000] {logging_mixin.py:190} INFO - [2025-03-15T07:06:19.855+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-15T07:06:19.861+0000] {logging_mixin.py:190} INFO - [2025-03-15T07:06:19.861+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-15T07:06:19.861+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-15T07:06:19.875+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.025 seconds
[2025-03-15T07:06:50.240+0000] {processor.py:186} INFO - Started process (PID=4355) to work on /opt/airflow/dags/A0265912B.py
[2025-03-15T07:06:50.241+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-15T07:06:50.243+0000] {logging_mixin.py:190} INFO - [2025-03-15T07:06:50.243+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-15T07:06:50.250+0000] {logging_mixin.py:190} INFO - [2025-03-15T07:06:50.249+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-15T07:06:50.250+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-15T07:06:50.263+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.025 seconds
[2025-03-15T07:07:20.594+0000] {processor.py:186} INFO - Started process (PID=4421) to work on /opt/airflow/dags/A0265912B.py
[2025-03-15T07:07:20.595+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-15T07:07:20.597+0000] {logging_mixin.py:190} INFO - [2025-03-15T07:07:20.596+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-15T07:07:20.603+0000] {logging_mixin.py:190} INFO - [2025-03-15T07:07:20.602+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-15T07:07:20.603+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-15T07:07:20.616+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.025 seconds
[2025-03-15T07:07:50.948+0000] {processor.py:186} INFO - Started process (PID=4487) to work on /opt/airflow/dags/A0265912B.py
[2025-03-15T07:07:50.949+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-15T07:07:50.950+0000] {logging_mixin.py:190} INFO - [2025-03-15T07:07:50.950+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-15T07:07:50.957+0000] {logging_mixin.py:190} INFO - [2025-03-15T07:07:50.956+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-15T07:07:50.957+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-15T07:07:50.974+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.029 seconds
[2025-03-15T07:08:21.367+0000] {processor.py:186} INFO - Started process (PID=4553) to work on /opt/airflow/dags/A0265912B.py
[2025-03-15T07:08:21.367+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-15T07:08:21.369+0000] {logging_mixin.py:190} INFO - [2025-03-15T07:08:21.369+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-15T07:08:21.375+0000] {logging_mixin.py:190} INFO - [2025-03-15T07:08:21.375+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-15T07:08:21.376+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-15T07:08:21.388+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.024 seconds
[2025-03-15T07:08:51.747+0000] {processor.py:186} INFO - Started process (PID=4619) to work on /opt/airflow/dags/A0265912B.py
[2025-03-15T07:08:51.748+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-15T07:08:51.750+0000] {logging_mixin.py:190} INFO - [2025-03-15T07:08:51.749+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-15T07:08:51.762+0000] {logging_mixin.py:190} INFO - [2025-03-15T07:08:51.758+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-15T07:08:51.762+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-15T07:08:51.779+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.034 seconds
[2025-03-15T07:09:22.034+0000] {processor.py:186} INFO - Started process (PID=4685) to work on /opt/airflow/dags/A0265912B.py
[2025-03-15T07:09:22.035+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-15T07:09:22.037+0000] {logging_mixin.py:190} INFO - [2025-03-15T07:09:22.037+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-15T07:09:22.046+0000] {logging_mixin.py:190} INFO - [2025-03-15T07:09:22.042+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-15T07:09:22.046+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-15T07:09:22.057+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.026 seconds
[2025-03-15T07:09:52.364+0000] {processor.py:186} INFO - Started process (PID=4750) to work on /opt/airflow/dags/A0265912B.py
[2025-03-15T07:09:52.365+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-15T07:09:52.367+0000] {logging_mixin.py:190} INFO - [2025-03-15T07:09:52.367+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-15T07:09:52.375+0000] {logging_mixin.py:190} INFO - [2025-03-15T07:09:52.372+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-15T07:09:52.376+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-15T07:09:52.385+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.023 seconds
[2025-03-15T07:10:22.672+0000] {processor.py:186} INFO - Started process (PID=4816) to work on /opt/airflow/dags/A0265912B.py
[2025-03-15T07:10:22.673+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-15T07:10:22.675+0000] {logging_mixin.py:190} INFO - [2025-03-15T07:10:22.675+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-15T07:10:22.688+0000] {logging_mixin.py:190} INFO - [2025-03-15T07:10:22.688+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-15T07:10:22.689+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-15T07:10:22.701+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.032 seconds
[2025-03-15T07:10:53.003+0000] {processor.py:186} INFO - Started process (PID=4882) to work on /opt/airflow/dags/A0265912B.py
[2025-03-15T07:10:53.004+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-15T07:10:53.005+0000] {logging_mixin.py:190} INFO - [2025-03-15T07:10:53.005+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-15T07:10:53.014+0000] {logging_mixin.py:190} INFO - [2025-03-15T07:10:53.013+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-15T07:10:53.014+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-15T07:10:53.025+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.024 seconds
[2025-03-15T07:11:23.320+0000] {processor.py:186} INFO - Started process (PID=4948) to work on /opt/airflow/dags/A0265912B.py
[2025-03-15T07:11:23.320+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-15T07:11:23.321+0000] {logging_mixin.py:190} INFO - [2025-03-15T07:11:23.321+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-15T07:11:23.328+0000] {logging_mixin.py:190} INFO - [2025-03-15T07:11:23.327+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-15T07:11:23.328+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-15T07:11:23.340+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.023 seconds
[2025-03-15T07:11:53.646+0000] {processor.py:186} INFO - Started process (PID=5014) to work on /opt/airflow/dags/A0265912B.py
[2025-03-15T07:11:53.647+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-15T07:11:53.649+0000] {logging_mixin.py:190} INFO - [2025-03-15T07:11:53.649+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-15T07:11:53.658+0000] {logging_mixin.py:190} INFO - [2025-03-15T07:11:53.655+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-15T07:11:53.659+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-15T07:11:53.669+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.026 seconds
[2025-03-15T07:12:23.955+0000] {processor.py:186} INFO - Started process (PID=5080) to work on /opt/airflow/dags/A0265912B.py
[2025-03-15T07:12:23.956+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-15T07:12:23.958+0000] {logging_mixin.py:190} INFO - [2025-03-15T07:12:23.958+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-15T07:12:23.965+0000] {logging_mixin.py:190} INFO - [2025-03-15T07:12:23.964+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-15T07:12:23.967+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-15T07:12:23.978+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.026 seconds
[2025-03-15T07:12:54.479+0000] {processor.py:186} INFO - Started process (PID=5146) to work on /opt/airflow/dags/A0265912B.py
[2025-03-15T07:12:54.480+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-15T07:12:54.481+0000] {logging_mixin.py:190} INFO - [2025-03-15T07:12:54.480+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-15T07:12:54.488+0000] {logging_mixin.py:190} INFO - [2025-03-15T07:12:54.484+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-15T07:12:54.490+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-15T07:12:54.500+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.024 seconds
[2025-03-15T07:13:24.661+0000] {processor.py:186} INFO - Started process (PID=5212) to work on /opt/airflow/dags/A0265912B.py
[2025-03-15T07:13:24.662+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-15T07:13:24.664+0000] {logging_mixin.py:190} INFO - [2025-03-15T07:13:24.664+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-15T07:13:24.673+0000] {logging_mixin.py:190} INFO - [2025-03-15T07:13:24.669+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-15T07:13:24.674+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-15T07:13:24.683+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.024 seconds
[2025-03-15T07:13:55.053+0000] {processor.py:186} INFO - Started process (PID=5278) to work on /opt/airflow/dags/A0265912B.py
[2025-03-15T07:13:55.054+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-15T07:13:55.056+0000] {logging_mixin.py:190} INFO - [2025-03-15T07:13:55.056+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-15T07:13:55.063+0000] {logging_mixin.py:190} INFO - [2025-03-15T07:13:55.062+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-15T07:13:55.063+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-15T07:13:55.075+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.024 seconds
[2025-03-15T07:14:25.340+0000] {processor.py:186} INFO - Started process (PID=5344) to work on /opt/airflow/dags/A0265912B.py
[2025-03-15T07:14:25.341+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-15T07:14:25.342+0000] {logging_mixin.py:190} INFO - [2025-03-15T07:14:25.342+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-15T07:14:25.351+0000] {logging_mixin.py:190} INFO - [2025-03-15T07:14:25.351+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-15T07:14:25.352+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-15T07:14:25.361+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.024 seconds
[2025-03-15T07:14:55.568+0000] {processor.py:186} INFO - Started process (PID=5410) to work on /opt/airflow/dags/A0265912B.py
[2025-03-15T07:14:55.569+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-15T07:14:55.571+0000] {logging_mixin.py:190} INFO - [2025-03-15T07:14:55.571+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-15T07:14:55.580+0000] {logging_mixin.py:190} INFO - [2025-03-15T07:14:55.576+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-15T07:14:55.581+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-15T07:14:55.594+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.027 seconds
[2025-03-15T07:15:25.811+0000] {processor.py:186} INFO - Started process (PID=5475) to work on /opt/airflow/dags/A0265912B.py
[2025-03-15T07:15:25.811+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-15T07:15:25.813+0000] {logging_mixin.py:190} INFO - [2025-03-15T07:15:25.813+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-15T07:15:25.828+0000] {logging_mixin.py:190} INFO - [2025-03-15T07:15:25.828+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-15T07:15:25.829+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-15T07:15:25.838+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.030 seconds
[2025-03-15T07:15:56.321+0000] {processor.py:186} INFO - Started process (PID=5541) to work on /opt/airflow/dags/A0265912B.py
[2025-03-15T07:15:56.323+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-15T07:15:56.324+0000] {logging_mixin.py:190} INFO - [2025-03-15T07:15:56.324+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-15T07:15:56.331+0000] {logging_mixin.py:190} INFO - [2025-03-15T07:15:56.331+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-15T07:15:56.332+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-15T07:15:56.341+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.023 seconds
[2025-03-15T07:16:26.773+0000] {processor.py:186} INFO - Started process (PID=5607) to work on /opt/airflow/dags/A0265912B.py
[2025-03-15T07:16:26.773+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-15T07:16:26.775+0000] {logging_mixin.py:190} INFO - [2025-03-15T07:16:26.774+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-15T07:16:26.781+0000] {logging_mixin.py:190} INFO - [2025-03-15T07:16:26.777+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-15T07:16:26.784+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-15T07:16:26.797+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.027 seconds
[2025-03-15T07:16:57.042+0000] {processor.py:186} INFO - Started process (PID=5672) to work on /opt/airflow/dags/A0265912B.py
[2025-03-15T07:16:57.043+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-15T07:16:57.045+0000] {logging_mixin.py:190} INFO - [2025-03-15T07:16:57.045+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-15T07:16:57.051+0000] {logging_mixin.py:190} INFO - [2025-03-15T07:16:57.050+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-15T07:16:57.051+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-15T07:16:57.060+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.020 seconds
[2025-03-15T07:17:27.329+0000] {processor.py:186} INFO - Started process (PID=5738) to work on /opt/airflow/dags/A0265912B.py
[2025-03-15T07:17:27.330+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-15T07:17:27.331+0000] {logging_mixin.py:190} INFO - [2025-03-15T07:17:27.331+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-15T07:17:27.338+0000] {logging_mixin.py:190} INFO - [2025-03-15T07:17:27.338+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-15T07:17:27.338+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-15T07:17:27.347+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.021 seconds
[2025-03-15T07:17:57.651+0000] {processor.py:186} INFO - Started process (PID=5804) to work on /opt/airflow/dags/A0265912B.py
[2025-03-15T07:17:57.652+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-15T07:17:57.653+0000] {logging_mixin.py:190} INFO - [2025-03-15T07:17:57.653+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-15T07:17:57.659+0000] {logging_mixin.py:190} INFO - [2025-03-15T07:17:57.659+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-15T07:17:57.660+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-15T07:17:57.671+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.023 seconds
[2025-03-15T07:18:27.869+0000] {processor.py:186} INFO - Started process (PID=5869) to work on /opt/airflow/dags/A0265912B.py
[2025-03-15T07:18:27.870+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-15T07:18:27.872+0000] {logging_mixin.py:190} INFO - [2025-03-15T07:18:27.872+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-15T07:18:27.878+0000] {logging_mixin.py:190} INFO - [2025-03-15T07:18:27.875+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-15T07:18:27.879+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-15T07:18:27.889+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.022 seconds
[2025-03-15T07:18:58.088+0000] {processor.py:186} INFO - Started process (PID=5935) to work on /opt/airflow/dags/A0265912B.py
[2025-03-15T07:18:58.088+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-15T07:18:58.089+0000] {logging_mixin.py:190} INFO - [2025-03-15T07:18:58.089+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-15T07:18:58.097+0000] {logging_mixin.py:190} INFO - [2025-03-15T07:18:58.093+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-15T07:18:58.097+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-15T07:18:58.107+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.022 seconds
[2025-03-15T07:19:28.448+0000] {processor.py:186} INFO - Started process (PID=6001) to work on /opt/airflow/dags/A0265912B.py
[2025-03-15T07:19:28.449+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-15T07:19:28.450+0000] {logging_mixin.py:190} INFO - [2025-03-15T07:19:28.450+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-15T07:19:28.458+0000] {logging_mixin.py:190} INFO - [2025-03-15T07:19:28.457+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-15T07:19:28.458+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-15T07:19:28.469+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.023 seconds
[2025-03-15T07:19:58.760+0000] {processor.py:186} INFO - Started process (PID=6067) to work on /opt/airflow/dags/A0265912B.py
[2025-03-15T07:19:58.760+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-15T07:19:58.761+0000] {logging_mixin.py:190} INFO - [2025-03-15T07:19:58.761+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-15T07:19:58.765+0000] {logging_mixin.py:190} INFO - [2025-03-15T07:19:58.764+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-15T07:19:58.768+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-15T07:19:58.777+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.020 seconds
[2025-03-15T07:20:28.959+0000] {processor.py:186} INFO - Started process (PID=6133) to work on /opt/airflow/dags/A0265912B.py
[2025-03-15T07:20:28.959+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-15T07:20:28.961+0000] {logging_mixin.py:190} INFO - [2025-03-15T07:20:28.961+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-15T07:20:28.968+0000] {logging_mixin.py:190} INFO - [2025-03-15T07:20:28.964+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-15T07:20:28.968+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-15T07:20:28.977+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.021 seconds
[2025-03-15T07:35:28.301+0000] {processor.py:186} INFO - Started process (PID=6170) to work on /opt/airflow/dags/A0265912B.py
[2025-03-15T07:35:28.301+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-15T07:35:28.303+0000] {logging_mixin.py:190} INFO - [2025-03-15T07:35:28.302+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-15T07:35:28.310+0000] {logging_mixin.py:190} INFO - [2025-03-15T07:35:28.308+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-15T07:35:28.310+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-15T07:35:28.319+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.020 seconds
[2025-03-15T07:35:58.804+0000] {processor.py:186} INFO - Started process (PID=6232) to work on /opt/airflow/dags/A0265912B.py
[2025-03-15T07:35:58.804+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-15T07:35:58.806+0000] {logging_mixin.py:190} INFO - [2025-03-15T07:35:58.806+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-15T07:35:58.811+0000] {logging_mixin.py:190} INFO - [2025-03-15T07:35:58.811+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-15T07:35:58.811+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-15T07:35:58.822+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.021 seconds
[2025-03-15T07:51:26.227+0000] {processor.py:186} INFO - Started process (PID=6298) to work on /opt/airflow/dags/A0265912B.py
[2025-03-15T07:51:26.233+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-15T07:51:26.236+0000] {logging_mixin.py:190} INFO - [2025-03-15T07:51:26.236+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-15T07:51:26.239+0000] {logging_mixin.py:190} INFO - [2025-03-15T07:51:26.238+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-15T07:51:26.239+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-15T07:51:26.248+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.023 seconds
[2025-03-15T07:51:57.203+0000] {processor.py:186} INFO - Started process (PID=6363) to work on /opt/airflow/dags/A0265912B.py
[2025-03-15T07:51:57.204+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-15T07:51:57.206+0000] {logging_mixin.py:190} INFO - [2025-03-15T07:51:57.206+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-15T07:51:57.212+0000] {logging_mixin.py:190} INFO - [2025-03-15T07:51:57.212+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-15T07:51:57.213+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-15T07:51:57.223+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.022 seconds
[2025-03-15T08:07:24.184+0000] {processor.py:186} INFO - Started process (PID=6429) to work on /opt/airflow/dags/A0265912B.py
[2025-03-15T08:07:24.185+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-15T08:07:24.187+0000] {logging_mixin.py:190} INFO - [2025-03-15T08:07:24.187+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-15T08:07:24.197+0000] {logging_mixin.py:190} INFO - [2025-03-15T08:07:24.193+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-15T08:07:24.197+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-15T08:07:24.211+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.029 seconds
[2025-03-15T08:07:54.662+0000] {processor.py:186} INFO - Started process (PID=6495) to work on /opt/airflow/dags/A0265912B.py
[2025-03-15T08:07:54.663+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-15T08:07:54.664+0000] {logging_mixin.py:190} INFO - [2025-03-15T08:07:54.663+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-15T08:07:54.671+0000] {logging_mixin.py:190} INFO - [2025-03-15T08:07:54.670+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-15T08:07:54.671+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-15T08:07:54.679+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.020 seconds
[2025-03-15T08:08:25.293+0000] {processor.py:186} INFO - Started process (PID=6561) to work on /opt/airflow/dags/A0265912B.py
[2025-03-15T08:08:25.294+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-15T08:08:25.295+0000] {logging_mixin.py:190} INFO - [2025-03-15T08:08:25.295+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-15T08:08:25.308+0000] {logging_mixin.py:190} INFO - [2025-03-15T08:08:25.303+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-15T08:08:25.308+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-15T08:08:25.318+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.028 seconds
[2025-03-15T08:08:55.732+0000] {processor.py:186} INFO - Started process (PID=6626) to work on /opt/airflow/dags/A0265912B.py
[2025-03-15T08:08:55.732+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-15T08:08:55.734+0000] {logging_mixin.py:190} INFO - [2025-03-15T08:08:55.734+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-15T08:08:55.740+0000] {logging_mixin.py:190} INFO - [2025-03-15T08:08:55.740+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-15T08:08:55.740+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-15T08:08:55.750+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.021 seconds
[2025-03-15T08:09:26.109+0000] {processor.py:186} INFO - Started process (PID=6697) to work on /opt/airflow/dags/A0265912B.py
[2025-03-15T08:09:26.110+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-15T08:09:26.111+0000] {logging_mixin.py:190} INFO - [2025-03-15T08:09:26.111+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-15T08:09:26.118+0000] {logging_mixin.py:190} INFO - [2025-03-15T08:09:26.116+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-15T08:09:26.118+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-15T08:09:26.127+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.021 seconds
[2025-03-15T08:09:56.865+0000] {processor.py:186} INFO - Started process (PID=6763) to work on /opt/airflow/dags/A0265912B.py
[2025-03-15T08:09:56.865+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-15T08:09:56.866+0000] {logging_mixin.py:190} INFO - [2025-03-15T08:09:56.866+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-15T08:09:56.876+0000] {logging_mixin.py:190} INFO - [2025-03-15T08:09:56.871+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-15T08:09:56.879+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-15T08:09:56.889+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.027 seconds
[2025-03-15T08:10:27.158+0000] {processor.py:186} INFO - Started process (PID=6829) to work on /opt/airflow/dags/A0265912B.py
[2025-03-15T08:10:27.159+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-15T08:10:27.160+0000] {logging_mixin.py:190} INFO - [2025-03-15T08:10:27.159+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-15T08:10:27.164+0000] {logging_mixin.py:190} INFO - [2025-03-15T08:10:27.162+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-15T08:10:27.166+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-15T08:10:27.178+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.023 seconds
[2025-03-15T08:10:57.377+0000] {processor.py:186} INFO - Started process (PID=6894) to work on /opt/airflow/dags/A0265912B.py
[2025-03-15T08:10:57.377+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-15T08:10:57.379+0000] {logging_mixin.py:190} INFO - [2025-03-15T08:10:57.379+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-15T08:10:57.385+0000] {logging_mixin.py:190} INFO - [2025-03-15T08:10:57.382+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-15T08:10:57.386+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-15T08:10:57.397+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.023 seconds
[2025-03-15T08:11:27.461+0000] {processor.py:186} INFO - Started process (PID=6960) to work on /opt/airflow/dags/A0265912B.py
[2025-03-15T08:11:27.462+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-15T08:11:27.464+0000] {logging_mixin.py:190} INFO - [2025-03-15T08:11:27.464+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-15T08:11:27.468+0000] {logging_mixin.py:190} INFO - [2025-03-15T08:11:27.468+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-15T08:11:27.470+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-15T08:11:27.480+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.022 seconds
[2025-03-15T08:26:52.389+0000] {processor.py:186} INFO - Started process (PID=7021) to work on /opt/airflow/dags/A0265912B.py
[2025-03-15T08:26:52.389+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-15T08:26:52.390+0000] {logging_mixin.py:190} INFO - [2025-03-15T08:26:52.390+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-15T08:26:52.400+0000] {logging_mixin.py:190} INFO - [2025-03-15T08:26:52.396+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-15T08:26:52.400+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-15T08:26:52.411+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.024 seconds
[2025-03-15T08:27:22.521+0000] {processor.py:186} INFO - Started process (PID=7086) to work on /opt/airflow/dags/A0265912B.py
[2025-03-15T08:27:22.522+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-15T08:27:22.523+0000] {logging_mixin.py:190} INFO - [2025-03-15T08:27:22.523+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-15T08:27:22.528+0000] {logging_mixin.py:190} INFO - [2025-03-15T08:27:22.526+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-15T08:27:22.528+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-15T08:27:22.538+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.020 seconds
[2025-03-15T08:27:52.788+0000] {processor.py:186} INFO - Started process (PID=7153) to work on /opt/airflow/dags/A0265912B.py
[2025-03-15T08:27:52.789+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-15T08:27:52.791+0000] {logging_mixin.py:190} INFO - [2025-03-15T08:27:52.791+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-15T08:27:52.796+0000] {logging_mixin.py:190} INFO - [2025-03-15T08:27:52.794+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-15T08:27:52.796+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-15T08:27:52.805+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.019 seconds
[2025-03-15T08:28:22.978+0000] {processor.py:186} INFO - Started process (PID=7219) to work on /opt/airflow/dags/A0265912B.py
[2025-03-15T08:28:22.978+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-15T08:28:22.980+0000] {logging_mixin.py:190} INFO - [2025-03-15T08:28:22.980+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-15T08:28:22.988+0000] {logging_mixin.py:190} INFO - [2025-03-15T08:28:22.985+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-15T08:28:22.989+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-15T08:28:23.006+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.030 seconds
[2025-03-15T08:28:53.345+0000] {processor.py:186} INFO - Started process (PID=7285) to work on /opt/airflow/dags/A0265912B.py
[2025-03-15T08:28:53.346+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-15T08:28:53.348+0000] {logging_mixin.py:190} INFO - [2025-03-15T08:28:53.347+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-15T08:28:53.354+0000] {logging_mixin.py:190} INFO - [2025-03-15T08:28:53.354+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-15T08:28:53.357+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-15T08:28:53.368+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.026 seconds
[2025-03-15T08:29:23.634+0000] {processor.py:186} INFO - Started process (PID=7351) to work on /opt/airflow/dags/A0265912B.py
[2025-03-15T08:29:23.635+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-15T08:29:23.637+0000] {logging_mixin.py:190} INFO - [2025-03-15T08:29:23.637+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-15T08:29:23.653+0000] {logging_mixin.py:190} INFO - [2025-03-15T08:29:23.652+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-15T08:29:23.653+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-15T08:29:23.662+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.030 seconds
[2025-03-15T08:29:53.793+0000] {processor.py:186} INFO - Started process (PID=7415) to work on /opt/airflow/dags/A0265912B.py
[2025-03-15T08:29:53.794+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-15T08:29:53.795+0000] {logging_mixin.py:190} INFO - [2025-03-15T08:29:53.795+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-15T08:29:53.802+0000] {logging_mixin.py:190} INFO - [2025-03-15T08:29:53.798+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-15T08:29:53.803+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-15T08:29:53.815+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.024 seconds
[2025-03-15T08:30:24.195+0000] {processor.py:186} INFO - Started process (PID=7482) to work on /opt/airflow/dags/A0265912B.py
[2025-03-15T08:30:24.196+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-15T08:30:24.198+0000] {logging_mixin.py:190} INFO - [2025-03-15T08:30:24.197+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-15T08:30:24.208+0000] {logging_mixin.py:190} INFO - [2025-03-15T08:30:24.207+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-15T08:30:24.208+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-15T08:30:24.220+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.027 seconds
[2025-03-15T08:30:54.432+0000] {processor.py:186} INFO - Started process (PID=7553) to work on /opt/airflow/dags/A0265912B.py
[2025-03-15T08:30:54.436+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-15T08:30:54.439+0000] {logging_mixin.py:190} INFO - [2025-03-15T08:30:54.439+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-15T08:30:54.444+0000] {logging_mixin.py:190} INFO - [2025-03-15T08:30:54.444+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-15T08:30:54.445+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-15T08:30:54.456+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.026 seconds
[2025-03-15T08:40:44.926+0000] {processor.py:186} INFO - Started process (PID=7613) to work on /opt/airflow/dags/A0265912B.py
[2025-03-15T08:40:44.926+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-15T08:40:44.928+0000] {logging_mixin.py:190} INFO - [2025-03-15T08:40:44.928+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-15T08:40:44.935+0000] {logging_mixin.py:190} INFO - [2025-03-15T08:40:44.934+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-15T08:40:44.935+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-15T08:40:44.946+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.023 seconds
[2025-03-15T08:41:54.682+0000] {processor.py:186} INFO - Started process (PID=7679) to work on /opt/airflow/dags/A0265912B.py
[2025-03-15T08:41:54.683+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-15T08:41:54.685+0000] {logging_mixin.py:190} INFO - [2025-03-15T08:41:54.685+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-15T08:41:54.691+0000] {logging_mixin.py:190} INFO - [2025-03-15T08:41:54.690+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-15T08:41:54.691+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-15T08:41:54.703+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.024 seconds
[2025-03-15T08:49:26.280+0000] {processor.py:186} INFO - Started process (PID=7745) to work on /opt/airflow/dags/A0265912B.py
[2025-03-15T08:49:26.280+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-15T08:49:26.281+0000] {logging_mixin.py:190} INFO - [2025-03-15T08:49:26.281+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-15T08:49:26.289+0000] {logging_mixin.py:190} INFO - [2025-03-15T08:49:26.288+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-15T08:49:26.289+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-15T08:49:26.297+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.020 seconds
[2025-03-15T09:20:12.730+0000] {processor.py:186} INFO - Started process (PID=7810) to work on /opt/airflow/dags/A0265912B.py
[2025-03-15T09:20:12.735+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-15T09:20:12.737+0000] {logging_mixin.py:190} INFO - [2025-03-15T09:20:12.737+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-15T09:20:12.743+0000] {logging_mixin.py:190} INFO - [2025-03-15T09:20:12.742+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-15T09:20:12.747+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-15T09:20:12.755+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.028 seconds
[2025-03-15T10:21:19.801+0000] {processor.py:186} INFO - Started process (PID=7876) to work on /opt/airflow/dags/A0265912B.py
[2025-03-15T10:21:19.802+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-15T10:21:19.804+0000] {logging_mixin.py:190} INFO - [2025-03-15T10:21:19.804+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-15T10:21:19.814+0000] {logging_mixin.py:190} INFO - [2025-03-15T10:21:19.814+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-15T10:21:19.815+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-15T10:21:19.824+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.026 seconds
[2025-03-15T11:22:22.551+0000] {processor.py:186} INFO - Started process (PID=7942) to work on /opt/airflow/dags/A0265912B.py
[2025-03-15T11:22:22.557+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-15T11:22:22.561+0000] {logging_mixin.py:190} INFO - [2025-03-15T11:22:22.560+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-15T11:22:22.568+0000] {logging_mixin.py:190} INFO - [2025-03-15T11:22:22.566+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-15T11:22:22.568+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-15T11:22:22.578+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.029 seconds
[2025-03-15T11:50:44.919+0000] {processor.py:186} INFO - Started process (PID=8008) to work on /opt/airflow/dags/A0265912B.py
[2025-03-15T11:50:44.920+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-15T11:50:44.921+0000] {logging_mixin.py:190} INFO - [2025-03-15T11:50:44.921+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-15T11:50:44.929+0000] {logging_mixin.py:190} INFO - [2025-03-15T11:50:44.925+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-15T11:50:44.929+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-15T11:50:44.940+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.023 seconds
[2025-03-15T13:24:08.696+0000] {processor.py:186} INFO - Started process (PID=8074) to work on /opt/airflow/dags/A0265912B.py
[2025-03-15T13:24:08.697+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-15T13:24:08.699+0000] {logging_mixin.py:190} INFO - [2025-03-15T13:24:08.699+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-15T13:24:08.709+0000] {logging_mixin.py:190} INFO - [2025-03-15T13:24:08.709+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-15T13:24:08.709+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-15T13:24:08.723+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.029 seconds
[2025-03-15T14:16:06.385+0000] {processor.py:186} INFO - Started process (PID=8140) to work on /opt/airflow/dags/A0265912B.py
[2025-03-15T14:16:06.385+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-15T14:16:06.387+0000] {logging_mixin.py:190} INFO - [2025-03-15T14:16:06.387+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-15T14:16:06.396+0000] {logging_mixin.py:190} INFO - [2025-03-15T14:16:06.395+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-15T14:16:06.396+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-15T14:16:06.407+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.024 seconds
[2025-03-15T15:26:10.549+0000] {processor.py:186} INFO - Started process (PID=8206) to work on /opt/airflow/dags/A0265912B.py
[2025-03-15T15:26:10.550+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-15T15:26:10.552+0000] {logging_mixin.py:190} INFO - [2025-03-15T15:26:10.551+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-15T15:26:10.557+0000] {logging_mixin.py:190} INFO - [2025-03-15T15:26:10.555+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-15T15:26:10.558+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-15T15:26:10.568+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.021 seconds
[2025-03-15T16:43:32.403+0000] {processor.py:186} INFO - Started process (PID=8272) to work on /opt/airflow/dags/A0265912B.py
[2025-03-15T16:43:32.404+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-15T16:43:32.406+0000] {logging_mixin.py:190} INFO - [2025-03-15T16:43:32.405+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-15T16:43:32.412+0000] {logging_mixin.py:190} INFO - [2025-03-15T16:43:32.411+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-15T16:43:32.412+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-15T16:43:32.424+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.023 seconds
[2025-03-15T18:01:32.335+0000] {processor.py:186} INFO - Started process (PID=8338) to work on /opt/airflow/dags/A0265912B.py
[2025-03-15T18:01:32.343+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-15T18:01:32.344+0000] {logging_mixin.py:190} INFO - [2025-03-15T18:01:32.344+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-15T18:01:32.351+0000] {logging_mixin.py:190} INFO - [2025-03-15T18:01:32.350+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-15T18:01:32.352+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-15T18:01:32.365+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.032 seconds
[2025-03-15T19:42:40.207+0000] {processor.py:186} INFO - Started process (PID=8404) to work on /opt/airflow/dags/A0265912B.py
[2025-03-15T19:42:40.207+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-15T19:42:40.209+0000] {logging_mixin.py:190} INFO - [2025-03-15T19:42:40.209+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-15T19:42:40.222+0000] {logging_mixin.py:190} INFO - [2025-03-15T19:42:40.222+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-15T19:42:40.223+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-15T19:42:40.231+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.027 seconds
[2025-03-15T21:02:39.260+0000] {processor.py:186} INFO - Started process (PID=8470) to work on /opt/airflow/dags/A0265912B.py
[2025-03-15T21:02:39.260+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-15T21:02:39.263+0000] {logging_mixin.py:190} INFO - [2025-03-15T21:02:39.262+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-15T21:02:39.270+0000] {logging_mixin.py:190} INFO - [2025-03-15T21:02:39.269+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-15T21:02:39.270+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-15T21:02:39.281+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.023 seconds
[2025-03-15T22:11:45.591+0000] {processor.py:186} INFO - Started process (PID=8536) to work on /opt/airflow/dags/A0265912B.py
[2025-03-15T22:11:45.596+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-15T22:11:45.599+0000] {logging_mixin.py:190} INFO - [2025-03-15T22:11:45.599+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-15T22:11:45.606+0000] {logging_mixin.py:190} INFO - [2025-03-15T22:11:45.605+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-15T22:11:45.606+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-15T22:11:45.657+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.070 seconds
[2025-03-15T23:50:12.324+0000] {processor.py:186} INFO - Started process (PID=8602) to work on /opt/airflow/dags/A0265912B.py
[2025-03-15T23:50:12.329+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-15T23:50:12.331+0000] {logging_mixin.py:190} INFO - [2025-03-15T23:50:12.331+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-15T23:50:12.336+0000] {logging_mixin.py:190} INFO - [2025-03-15T23:50:12.336+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-15T23:50:12.339+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-15T23:50:12.349+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.028 seconds
