[2025-03-14T11:07:50.235+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-14T11:07:50.242+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ecommerce_etl_taskflow.load manual__2025-03-14T11:07:46.028917+00:00 [queued]>
[2025-03-14T11:07:50.245+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ecommerce_etl_taskflow.load manual__2025-03-14T11:07:46.028917+00:00 [queued]>
[2025-03-14T11:07:50.245+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 4
[2025-03-14T11:07:50.249+0000] {taskinstance.py:2890} INFO - Executing <Task(_PythonDecoratedOperator): load> on 2025-03-14 11:07:46.028917+00:00
[2025-03-14T11:07:50.251+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=152) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-14T11:07:50.252+0000] {standard_task_runner.py:72} INFO - Started process 153 to run task
[2025-03-14T11:07:50.252+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'ecommerce_etl_taskflow', 'load', 'manual__2025-03-14T11:07:46.028917+00:00', '--job-id', '44', '--raw', '--subdir', 'DAGS_FOLDER/IS3107 Data Engineering DAG Demo Taskflow.py', '--cfg-path', '/tmp/tmple8cotkk']
[2025-03-14T11:07:50.253+0000] {standard_task_runner.py:105} INFO - Job 44: Subtask load
[2025-03-14T11:07:50.278+0000] {task_command.py:467} INFO - Running <TaskInstance: ecommerce_etl_taskflow.load manual__2025-03-14T11:07:46.028917+00:00 [running]> on host c9040eb62b77
[2025-03-14T11:07:50.403+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='***@example.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ecommerce_etl_taskflow' AIRFLOW_CTX_TASK_ID='load' AIRFLOW_CTX_EXECUTION_DATE='2025-03-14T11:07:46.028917+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-14T11:07:46.028917+00:00'
[2025-03-14T11:07:50.403+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-14T11:07:50.403+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-14T11:07:50.403+0000] {logging_mixin.py:190} INFO - Current task name:load state:running start_date:2025-03-14 11:07:50.242699+00:00
[2025-03-14T11:07:50.403+0000] {logging_mixin.py:190} INFO - Dag name:ecommerce_etl_taskflow and current dag run status:running
[2025-03-14T11:07:50.404+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-14T11:07:50.407+0000] {base.py:84} INFO - Retrieving connection 'postgres_t5'
[2025-03-14T11:07:50.408+0000] {sql.py:511} INFO - Running statement: 
        INSERT INTO orders (order_id, customer_id, amount, status)
        VALUES (%(order_id)s, %(customer_id)s, %(amount)s, %(status)s);
        , parameters: {'order_id': 0, 'customer_id': 123, 'amount': 110.00000000000001, 'status': 'completed'}
[2025-03-14T11:07:50.409+0000] {sql.py:520} INFO - Rows affected: 1
[2025-03-14T11:07:50.409+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-14T11:07:50.412+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-14T11:07:50.412+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=ecommerce_etl_taskflow, task_id=load, run_id=manual__2025-03-14T11:07:46.028917+00:00, execution_date=20250314T110746, start_date=20250314T110750, end_date=20250314T110750
[2025-03-14T11:07:50.420+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-03-14T11:07:50.420+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-03-14T11:07:50.420+0000] {logging_mixin.py:190} INFO - Dag name:ecommerce_etl_taskflow queued_at:2025-03-14 11:07:46.038527+00:00
[2025-03-14T11:07:50.420+0000] {logging_mixin.py:190} INFO - Task hostname:c9040eb62b77 operator:_PythonDecoratedOperator
[2025-03-14T11:07:50.443+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-14T11:07:50.450+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-14T11:07:50.450+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
