[2025-03-17T00:45:32.514+0000] {processor.py:186} INFO - Started process (PID=10047) to work on /opt/airflow/dags/A0265912B.py
[2025-03-17T00:45:32.515+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-17T00:45:32.517+0000] {logging_mixin.py:190} INFO - [2025-03-17T00:45:32.517+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-17T00:45:32.524+0000] {logging_mixin.py:190} INFO - [2025-03-17T00:45:32.522+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-17T00:45:32.524+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-17T00:45:32.532+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.020 seconds
[2025-03-17T02:11:08.111+0000] {processor.py:186} INFO - Started process (PID=10113) to work on /opt/airflow/dags/A0265912B.py
[2025-03-17T02:11:08.112+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-17T02:11:08.113+0000] {logging_mixin.py:190} INFO - [2025-03-17T02:11:08.113+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-17T02:11:08.121+0000] {logging_mixin.py:190} INFO - [2025-03-17T02:11:08.117+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-17T02:11:08.121+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-17T02:11:08.131+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.022 seconds
[2025-03-17T02:30:12.930+0000] {processor.py:186} INFO - Started process (PID=10179) to work on /opt/airflow/dags/A0265912B.py
[2025-03-17T02:30:12.931+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-17T02:30:12.933+0000] {logging_mixin.py:190} INFO - [2025-03-17T02:30:12.933+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-17T02:30:12.940+0000] {logging_mixin.py:190} INFO - [2025-03-17T02:30:12.936+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-17T02:30:12.940+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-17T02:30:12.950+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.022 seconds
[2025-03-17T02:30:43.336+0000] {processor.py:186} INFO - Started process (PID=10245) to work on /opt/airflow/dags/A0265912B.py
[2025-03-17T02:30:43.337+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-17T02:30:43.338+0000] {logging_mixin.py:190} INFO - [2025-03-17T02:30:43.338+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-17T02:30:43.342+0000] {logging_mixin.py:190} INFO - [2025-03-17T02:30:43.341+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-17T02:30:43.342+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-17T02:30:43.351+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.017 seconds
[2025-03-17T02:31:13.848+0000] {processor.py:186} INFO - Started process (PID=10311) to work on /opt/airflow/dags/A0265912B.py
[2025-03-17T02:31:13.849+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-17T02:31:13.850+0000] {logging_mixin.py:190} INFO - [2025-03-17T02:31:13.850+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-17T02:31:13.860+0000] {logging_mixin.py:190} INFO - [2025-03-17T02:31:13.854+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-17T02:31:13.860+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-17T02:31:13.872+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.028 seconds
[2025-03-17T02:31:44.384+0000] {processor.py:186} INFO - Started process (PID=10377) to work on /opt/airflow/dags/A0265912B.py
[2025-03-17T02:31:44.385+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-17T02:31:44.386+0000] {logging_mixin.py:190} INFO - [2025-03-17T02:31:44.386+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-17T02:31:44.393+0000] {logging_mixin.py:190} INFO - [2025-03-17T02:31:44.392+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-17T02:31:44.393+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-17T02:31:44.402+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.021 seconds
[2025-03-17T02:32:14.848+0000] {processor.py:186} INFO - Started process (PID=10443) to work on /opt/airflow/dags/A0265912B.py
[2025-03-17T02:32:14.848+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-17T02:32:14.849+0000] {logging_mixin.py:190} INFO - [2025-03-17T02:32:14.849+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-17T02:32:14.856+0000] {logging_mixin.py:190} INFO - [2025-03-17T02:32:14.853+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-17T02:32:14.857+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-17T02:32:14.865+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.019 seconds
[2025-03-17T02:32:45.337+0000] {processor.py:186} INFO - Started process (PID=10509) to work on /opt/airflow/dags/A0265912B.py
[2025-03-17T02:32:45.338+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-17T02:32:45.339+0000] {logging_mixin.py:190} INFO - [2025-03-17T02:32:45.339+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-17T02:32:45.349+0000] {logging_mixin.py:190} INFO - [2025-03-17T02:32:45.344+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-17T02:32:45.350+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-17T02:32:45.364+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.029 seconds
[2025-03-17T02:33:15.693+0000] {processor.py:186} INFO - Started process (PID=10575) to work on /opt/airflow/dags/A0265912B.py
[2025-03-17T02:33:15.694+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-17T02:33:15.695+0000] {logging_mixin.py:190} INFO - [2025-03-17T02:33:15.695+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-17T02:33:15.701+0000] {logging_mixin.py:190} INFO - [2025-03-17T02:33:15.699+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-17T02:33:15.703+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-17T02:33:15.714+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.024 seconds
[2025-03-17T02:33:46.478+0000] {processor.py:186} INFO - Started process (PID=10641) to work on /opt/airflow/dags/A0265912B.py
[2025-03-17T02:33:46.479+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-17T02:33:46.481+0000] {logging_mixin.py:190} INFO - [2025-03-17T02:33:46.481+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-17T02:33:46.488+0000] {logging_mixin.py:190} INFO - [2025-03-17T02:33:46.487+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-17T02:33:46.492+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-17T02:33:46.502+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.026 seconds
[2025-03-17T02:34:16.949+0000] {processor.py:186} INFO - Started process (PID=10713) to work on /opt/airflow/dags/A0265912B.py
[2025-03-17T02:34:16.949+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-17T02:34:16.950+0000] {logging_mixin.py:190} INFO - [2025-03-17T02:34:16.950+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-17T02:34:16.955+0000] {logging_mixin.py:190} INFO - [2025-03-17T02:34:16.954+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-17T02:34:16.955+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-17T02:34:16.964+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.018 seconds
[2025-03-17T02:34:47.330+0000] {processor.py:186} INFO - Started process (PID=10779) to work on /opt/airflow/dags/A0265912B.py
[2025-03-17T02:34:47.331+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-17T02:34:47.332+0000] {logging_mixin.py:190} INFO - [2025-03-17T02:34:47.332+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-17T02:34:47.340+0000] {logging_mixin.py:190} INFO - [2025-03-17T02:34:47.335+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-17T02:34:47.340+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-17T02:34:47.352+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.025 seconds
[2025-03-17T02:35:17.678+0000] {processor.py:186} INFO - Started process (PID=10845) to work on /opt/airflow/dags/A0265912B.py
[2025-03-17T02:35:17.678+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-17T02:35:17.680+0000] {logging_mixin.py:190} INFO - [2025-03-17T02:35:17.680+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-17T02:35:17.687+0000] {logging_mixin.py:190} INFO - [2025-03-17T02:35:17.687+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-17T02:35:17.688+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-17T02:35:17.698+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.023 seconds
[2025-03-17T02:35:47.988+0000] {processor.py:186} INFO - Started process (PID=10911) to work on /opt/airflow/dags/A0265912B.py
[2025-03-17T02:35:47.989+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-17T02:35:47.991+0000] {logging_mixin.py:190} INFO - [2025-03-17T02:35:47.991+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-17T02:35:47.997+0000] {logging_mixin.py:190} INFO - [2025-03-17T02:35:47.993+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-17T02:35:47.997+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-17T02:35:48.007+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.021 seconds
[2025-03-17T02:36:18.403+0000] {processor.py:186} INFO - Started process (PID=10977) to work on /opt/airflow/dags/A0265912B.py
[2025-03-17T02:36:18.404+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-17T02:36:18.406+0000] {logging_mixin.py:190} INFO - [2025-03-17T02:36:18.406+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-17T02:36:18.417+0000] {logging_mixin.py:190} INFO - [2025-03-17T02:36:18.410+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-17T02:36:18.417+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-17T02:36:18.425+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.024 seconds
[2025-03-17T02:36:48.766+0000] {processor.py:186} INFO - Started process (PID=11043) to work on /opt/airflow/dags/A0265912B.py
[2025-03-17T02:36:48.766+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-17T02:36:48.768+0000] {logging_mixin.py:190} INFO - [2025-03-17T02:36:48.768+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-17T02:36:48.779+0000] {logging_mixin.py:190} INFO - [2025-03-17T02:36:48.775+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-17T02:36:48.779+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-17T02:36:48.790+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.027 seconds
[2025-03-17T02:37:19.435+0000] {processor.py:186} INFO - Started process (PID=11109) to work on /opt/airflow/dags/A0265912B.py
[2025-03-17T02:37:19.436+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-17T02:37:19.437+0000] {logging_mixin.py:190} INFO - [2025-03-17T02:37:19.437+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-17T02:37:19.444+0000] {logging_mixin.py:190} INFO - [2025-03-17T02:37:19.440+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-17T02:37:19.445+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-17T02:37:19.455+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.022 seconds
[2025-03-17T02:37:49.867+0000] {processor.py:186} INFO - Started process (PID=11175) to work on /opt/airflow/dags/A0265912B.py
[2025-03-17T02:37:49.867+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-17T02:37:49.869+0000] {logging_mixin.py:190} INFO - [2025-03-17T02:37:49.869+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-17T02:37:49.881+0000] {logging_mixin.py:190} INFO - [2025-03-17T02:37:49.874+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-17T02:37:49.882+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-17T02:37:49.895+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.030 seconds
[2025-03-17T02:38:20.138+0000] {processor.py:186} INFO - Started process (PID=11241) to work on /opt/airflow/dags/A0265912B.py
[2025-03-17T02:38:20.139+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-17T02:38:20.141+0000] {logging_mixin.py:190} INFO - [2025-03-17T02:38:20.141+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-17T02:38:20.150+0000] {logging_mixin.py:190} INFO - [2025-03-17T02:38:20.149+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-17T02:38:20.150+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-17T02:38:20.162+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.026 seconds
[2025-03-17T02:38:50.413+0000] {processor.py:186} INFO - Started process (PID=11307) to work on /opt/airflow/dags/A0265912B.py
[2025-03-17T02:38:50.414+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-17T02:38:50.415+0000] {logging_mixin.py:190} INFO - [2025-03-17T02:38:50.415+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-17T02:38:50.422+0000] {logging_mixin.py:190} INFO - [2025-03-17T02:38:50.421+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-17T02:38:50.424+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-17T02:38:50.436+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.026 seconds
[2025-03-17T02:39:20.708+0000] {processor.py:186} INFO - Started process (PID=11373) to work on /opt/airflow/dags/A0265912B.py
[2025-03-17T02:39:20.708+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-17T02:39:20.710+0000] {logging_mixin.py:190} INFO - [2025-03-17T02:39:20.710+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-17T02:39:20.718+0000] {logging_mixin.py:190} INFO - [2025-03-17T02:39:20.715+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-17T02:39:20.718+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-17T02:39:20.728+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.023 seconds
[2025-03-17T02:39:50.830+0000] {processor.py:186} INFO - Started process (PID=11437) to work on /opt/airflow/dags/A0265912B.py
[2025-03-17T02:39:50.831+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-17T02:39:50.832+0000] {logging_mixin.py:190} INFO - [2025-03-17T02:39:50.832+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-17T02:39:50.839+0000] {logging_mixin.py:190} INFO - [2025-03-17T02:39:50.838+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-17T02:39:50.840+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-17T02:39:50.850+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.023 seconds
[2025-03-17T02:40:20.963+0000] {processor.py:186} INFO - Started process (PID=11503) to work on /opt/airflow/dags/A0265912B.py
[2025-03-17T02:40:20.964+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-17T02:40:20.965+0000] {logging_mixin.py:190} INFO - [2025-03-17T02:40:20.965+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-17T02:40:20.969+0000] {logging_mixin.py:190} INFO - [2025-03-17T02:40:20.968+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-17T02:40:20.971+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-17T02:40:20.982+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.021 seconds
[2025-03-17T02:40:51.172+0000] {processor.py:186} INFO - Started process (PID=11569) to work on /opt/airflow/dags/A0265912B.py
[2025-03-17T02:40:51.172+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-17T02:40:51.176+0000] {logging_mixin.py:190} INFO - [2025-03-17T02:40:51.175+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-17T02:40:51.181+0000] {logging_mixin.py:190} INFO - [2025-03-17T02:40:51.179+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-17T02:40:51.194+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-17T02:40:51.207+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.038 seconds
[2025-03-17T02:41:21.330+0000] {processor.py:186} INFO - Started process (PID=11635) to work on /opt/airflow/dags/A0265912B.py
[2025-03-17T02:41:21.331+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-17T02:41:21.332+0000] {logging_mixin.py:190} INFO - [2025-03-17T02:41:21.332+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-17T02:41:21.335+0000] {logging_mixin.py:190} INFO - [2025-03-17T02:41:21.335+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-17T02:41:21.336+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-17T02:41:21.347+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.019 seconds
[2025-03-17T02:41:51.385+0000] {processor.py:186} INFO - Started process (PID=11701) to work on /opt/airflow/dags/A0265912B.py
[2025-03-17T02:41:51.385+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-17T02:41:51.387+0000] {logging_mixin.py:190} INFO - [2025-03-17T02:41:51.387+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-17T02:41:51.390+0000] {logging_mixin.py:190} INFO - [2025-03-17T02:41:51.389+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-17T02:41:51.391+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-17T02:41:51.402+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.020 seconds
[2025-03-17T02:42:21.691+0000] {processor.py:186} INFO - Started process (PID=11767) to work on /opt/airflow/dags/A0265912B.py
[2025-03-17T02:42:21.692+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-17T02:42:21.693+0000] {logging_mixin.py:190} INFO - [2025-03-17T02:42:21.693+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-17T02:42:21.700+0000] {logging_mixin.py:190} INFO - [2025-03-17T02:42:21.696+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-17T02:42:21.700+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-17T02:42:21.710+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.021 seconds
[2025-03-17T02:58:30.451+0000] {processor.py:186} INFO - Started process (PID=11828) to work on /opt/airflow/dags/A0265912B.py
[2025-03-17T02:58:30.452+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-17T02:58:30.453+0000] {logging_mixin.py:190} INFO - [2025-03-17T02:58:30.453+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-17T02:58:30.464+0000] {logging_mixin.py:190} INFO - [2025-03-17T02:58:30.464+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-17T02:58:30.465+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-17T02:58:30.474+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.025 seconds
[2025-03-17T04:07:30.804+0000] {processor.py:186} INFO - Started process (PID=11894) to work on /opt/airflow/dags/A0265912B.py
[2025-03-17T04:07:30.805+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-17T04:07:30.808+0000] {logging_mixin.py:190} INFO - [2025-03-17T04:07:30.807+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-17T04:07:30.822+0000] {logging_mixin.py:190} INFO - [2025-03-17T04:07:30.821+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-17T04:07:30.823+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-17T04:07:30.834+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.033 seconds
[2025-03-17T05:18:08.495+0000] {processor.py:186} INFO - Started process (PID=11960) to work on /opt/airflow/dags/A0265912B.py
[2025-03-17T05:18:08.496+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-17T05:18:08.498+0000] {logging_mixin.py:190} INFO - [2025-03-17T05:18:08.497+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-17T05:18:08.505+0000] {logging_mixin.py:190} INFO - [2025-03-17T05:18:08.501+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-17T05:18:08.505+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-17T05:18:08.514+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.022 seconds
[2025-03-17T05:57:31.333+0000] {processor.py:186} INFO - Started process (PID=12026) to work on /opt/airflow/dags/A0265912B.py
[2025-03-17T05:57:31.334+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-17T05:57:31.335+0000] {logging_mixin.py:190} INFO - [2025-03-17T05:57:31.335+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-17T05:57:31.343+0000] {logging_mixin.py:190} INFO - [2025-03-17T05:57:31.339+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-17T05:57:31.344+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-17T05:57:31.355+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.025 seconds
[2025-03-17T05:59:13.762+0000] {processor.py:186} INFO - Started process (PID=12092) to work on /opt/airflow/dags/A0265912B.py
[2025-03-17T05:59:13.762+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-17T05:59:13.765+0000] {logging_mixin.py:190} INFO - [2025-03-17T05:59:13.765+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-17T05:59:13.774+0000] {logging_mixin.py:190} INFO - [2025-03-17T05:59:13.770+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-17T05:59:13.774+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-17T05:59:13.786+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.027 seconds
[2025-03-17T06:00:02.307+0000] {processor.py:186} INFO - Started process (PID=12158) to work on /opt/airflow/dags/A0265912B.py
[2025-03-17T06:00:02.308+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-17T06:00:02.310+0000] {logging_mixin.py:190} INFO - [2025-03-17T06:00:02.310+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-17T06:00:02.316+0000] {logging_mixin.py:190} INFO - [2025-03-17T06:00:02.315+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-17T06:00:02.316+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-17T06:00:02.328+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.023 seconds
[2025-03-17T06:02:12.948+0000] {processor.py:186} INFO - Started process (PID=12224) to work on /opt/airflow/dags/A0265912B.py
[2025-03-17T06:02:12.949+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-17T06:02:12.950+0000] {logging_mixin.py:190} INFO - [2025-03-17T06:02:12.950+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-17T06:02:12.957+0000] {logging_mixin.py:190} INFO - [2025-03-17T06:02:12.953+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-17T06:02:12.958+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-17T06:02:12.968+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.022 seconds
[2025-03-17T06:03:59.546+0000] {processor.py:186} INFO - Started process (PID=12290) to work on /opt/airflow/dags/A0265912B.py
[2025-03-17T06:03:59.547+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-17T06:03:59.547+0000] {logging_mixin.py:190} INFO - [2025-03-17T06:03:59.547+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-17T06:03:59.558+0000] {logging_mixin.py:190} INFO - [2025-03-17T06:03:59.558+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-17T06:03:59.559+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-17T06:03:59.571+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.027 seconds
[2025-03-17T06:09:15.854+0000] {processor.py:186} INFO - Started process (PID=12356) to work on /opt/airflow/dags/A0265912B.py
[2025-03-17T06:09:15.855+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-17T06:09:15.857+0000] {logging_mixin.py:190} INFO - [2025-03-17T06:09:15.857+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-17T06:09:15.873+0000] {logging_mixin.py:190} INFO - [2025-03-17T06:09:15.871+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-17T06:09:15.874+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-17T06:09:15.884+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.033 seconds
[2025-03-17T06:23:35.626+0000] {processor.py:186} INFO - Started process (PID=12422) to work on /opt/airflow/dags/A0265912B.py
[2025-03-17T06:23:35.626+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-17T06:23:35.628+0000] {logging_mixin.py:190} INFO - [2025-03-17T06:23:35.628+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-17T06:23:35.634+0000] {logging_mixin.py:190} INFO - [2025-03-17T06:23:35.631+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-17T06:23:35.634+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-17T06:23:35.644+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.020 seconds
[2025-03-17T06:24:06.065+0000] {processor.py:186} INFO - Started process (PID=12488) to work on /opt/airflow/dags/A0265912B.py
[2025-03-17T06:24:06.066+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-17T06:24:06.067+0000] {logging_mixin.py:190} INFO - [2025-03-17T06:24:06.067+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-17T06:24:06.075+0000] {logging_mixin.py:190} INFO - [2025-03-17T06:24:06.074+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-17T06:24:06.076+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-17T06:24:06.087+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.025 seconds
[2025-03-17T06:24:36.632+0000] {processor.py:186} INFO - Started process (PID=12554) to work on /opt/airflow/dags/A0265912B.py
[2025-03-17T06:24:36.633+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-17T06:24:36.633+0000] {logging_mixin.py:190} INFO - [2025-03-17T06:24:36.633+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-17T06:24:36.644+0000] {logging_mixin.py:190} INFO - [2025-03-17T06:24:36.637+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-17T06:24:36.644+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-17T06:24:36.653+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.024 seconds
[2025-03-17T06:25:07.332+0000] {processor.py:186} INFO - Started process (PID=12620) to work on /opt/airflow/dags/A0265912B.py
[2025-03-17T06:25:07.332+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-17T06:25:07.334+0000] {logging_mixin.py:190} INFO - [2025-03-17T06:25:07.334+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-17T06:25:07.338+0000] {logging_mixin.py:190} INFO - [2025-03-17T06:25:07.337+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-17T06:25:07.338+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-17T06:25:07.348+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.018 seconds
[2025-03-17T06:25:37.830+0000] {processor.py:186} INFO - Started process (PID=12686) to work on /opt/airflow/dags/A0265912B.py
[2025-03-17T06:25:37.831+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-17T06:25:37.832+0000] {logging_mixin.py:190} INFO - [2025-03-17T06:25:37.832+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-17T06:25:37.839+0000] {logging_mixin.py:190} INFO - [2025-03-17T06:25:37.838+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-17T06:25:37.839+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-17T06:25:37.849+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.021 seconds
[2025-03-17T06:26:08.232+0000] {processor.py:186} INFO - Started process (PID=12752) to work on /opt/airflow/dags/A0265912B.py
[2025-03-17T06:26:08.232+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-17T06:26:08.234+0000] {logging_mixin.py:190} INFO - [2025-03-17T06:26:08.234+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-17T06:26:08.244+0000] {logging_mixin.py:190} INFO - [2025-03-17T06:26:08.238+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-17T06:26:08.244+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-17T06:26:08.253+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.024 seconds
[2025-03-17T06:26:38.796+0000] {processor.py:186} INFO - Started process (PID=12818) to work on /opt/airflow/dags/A0265912B.py
[2025-03-17T06:26:38.797+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-17T06:26:38.799+0000] {logging_mixin.py:190} INFO - [2025-03-17T06:26:38.798+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-17T06:26:38.806+0000] {logging_mixin.py:190} INFO - [2025-03-17T06:26:38.805+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-17T06:26:38.806+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-17T06:26:38.815+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.021 seconds
[2025-03-17T06:27:09.138+0000] {processor.py:186} INFO - Started process (PID=12884) to work on /opt/airflow/dags/A0265912B.py
[2025-03-17T06:27:09.138+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-17T06:27:09.140+0000] {logging_mixin.py:190} INFO - [2025-03-17T06:27:09.140+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-17T06:27:09.154+0000] {logging_mixin.py:190} INFO - [2025-03-17T06:27:09.150+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-17T06:27:09.154+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-17T06:27:09.164+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.028 seconds
[2025-03-17T06:27:39.462+0000] {processor.py:186} INFO - Started process (PID=12950) to work on /opt/airflow/dags/A0265912B.py
[2025-03-17T06:27:39.463+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-17T06:27:39.464+0000] {logging_mixin.py:190} INFO - [2025-03-17T06:27:39.464+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-17T06:27:39.471+0000] {logging_mixin.py:190} INFO - [2025-03-17T06:27:39.471+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-17T06:27:39.471+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-17T06:27:39.484+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.024 seconds
[2025-03-17T06:28:10.146+0000] {processor.py:186} INFO - Started process (PID=13016) to work on /opt/airflow/dags/A0265912B.py
[2025-03-17T06:28:10.147+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-17T06:28:10.148+0000] {logging_mixin.py:190} INFO - [2025-03-17T06:28:10.148+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-17T06:28:10.155+0000] {logging_mixin.py:190} INFO - [2025-03-17T06:28:10.154+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-17T06:28:10.159+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-17T06:28:10.167+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.023 seconds
