[2025-03-16T01:29:03.320+0000] {processor.py:186} INFO - Started process (PID=8667) to work on /opt/airflow/dags/A0265912B.py
[2025-03-16T01:29:03.320+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-16T01:29:03.323+0000] {logging_mixin.py:190} INFO - [2025-03-16T01:29:03.323+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-16T01:29:03.330+0000] {logging_mixin.py:190} INFO - [2025-03-16T01:29:03.327+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-16T01:29:03.331+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-16T01:29:03.342+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.024 seconds
[2025-03-16T02:50:13.493+0000] {processor.py:186} INFO - Started process (PID=8734) to work on /opt/airflow/dags/A0265912B.py
[2025-03-16T02:50:13.493+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-16T02:50:13.495+0000] {logging_mixin.py:190} INFO - [2025-03-16T02:50:13.495+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-16T02:50:13.503+0000] {logging_mixin.py:190} INFO - [2025-03-16T02:50:13.499+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-16T02:50:13.503+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-16T02:50:13.513+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.023 seconds
[2025-03-16T04:04:20.218+0000] {processor.py:186} INFO - Started process (PID=8800) to work on /opt/airflow/dags/A0265912B.py
[2025-03-16T04:04:20.219+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-16T04:04:20.222+0000] {logging_mixin.py:190} INFO - [2025-03-16T04:04:20.222+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-16T04:04:20.231+0000] {logging_mixin.py:190} INFO - [2025-03-16T04:04:20.229+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-16T04:04:20.231+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-16T04:04:20.243+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.029 seconds
[2025-03-16T05:14:52.285+0000] {processor.py:186} INFO - Started process (PID=8865) to work on /opt/airflow/dags/A0265912B.py
[2025-03-16T05:14:52.285+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-16T05:14:52.288+0000] {logging_mixin.py:190} INFO - [2025-03-16T05:14:52.287+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-16T05:14:52.294+0000] {logging_mixin.py:190} INFO - [2025-03-16T05:14:52.294+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-16T05:14:52.295+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-16T05:14:52.305+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.023 seconds
[2025-03-16T06:06:44.746+0000] {processor.py:186} INFO - Started process (PID=8931) to work on /opt/airflow/dags/A0265912B.py
[2025-03-16T06:06:44.752+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-16T06:06:44.753+0000] {logging_mixin.py:190} INFO - [2025-03-16T06:06:44.753+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-16T06:06:44.759+0000] {logging_mixin.py:190} INFO - [2025-03-16T06:06:44.758+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-16T06:06:44.760+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-16T06:06:44.771+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.027 seconds
[2025-03-16T07:16:47.843+0000] {processor.py:186} INFO - Started process (PID=8997) to work on /opt/airflow/dags/A0265912B.py
[2025-03-16T07:16:47.843+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-16T07:16:47.845+0000] {logging_mixin.py:190} INFO - [2025-03-16T07:16:47.845+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-16T07:16:47.856+0000] {logging_mixin.py:190} INFO - [2025-03-16T07:16:47.852+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-16T07:16:47.857+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-16T07:16:47.869+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.028 seconds
[2025-03-16T08:08:40.154+0000] {processor.py:186} INFO - Started process (PID=9062) to work on /opt/airflow/dags/A0265912B.py
[2025-03-16T08:08:40.154+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-16T08:08:40.155+0000] {logging_mixin.py:190} INFO - [2025-03-16T08:08:40.155+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-16T08:08:40.162+0000] {logging_mixin.py:190} INFO - [2025-03-16T08:08:40.161+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-16T08:08:40.162+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-16T08:08:40.172+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.020 seconds
[2025-03-16T09:18:50.183+0000] {processor.py:186} INFO - Started process (PID=9127) to work on /opt/airflow/dags/A0265912B.py
[2025-03-16T09:18:50.183+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-16T09:18:50.185+0000] {logging_mixin.py:190} INFO - [2025-03-16T09:18:50.185+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-16T09:18:50.192+0000] {logging_mixin.py:190} INFO - [2025-03-16T09:18:50.191+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-16T09:18:50.192+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-16T09:18:50.205+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.024 seconds
[2025-03-16T10:37:09.184+0000] {processor.py:186} INFO - Started process (PID=9193) to work on /opt/airflow/dags/A0265912B.py
[2025-03-16T10:37:09.185+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-16T10:37:09.187+0000] {logging_mixin.py:190} INFO - [2025-03-16T10:37:09.186+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-16T10:37:09.194+0000] {logging_mixin.py:190} INFO - [2025-03-16T10:37:09.194+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-16T10:37:09.195+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-16T10:37:09.204+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.022 seconds
[2025-03-16T11:55:35.268+0000] {processor.py:186} INFO - Started process (PID=9259) to work on /opt/airflow/dags/A0265912B.py
[2025-03-16T11:55:35.269+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-16T11:55:35.270+0000] {logging_mixin.py:190} INFO - [2025-03-16T11:55:35.270+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-16T11:55:35.280+0000] {logging_mixin.py:190} INFO - [2025-03-16T11:55:35.274+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-16T11:55:35.280+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-16T11:55:35.293+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.028 seconds
[2025-03-16T13:22:46.976+0000] {processor.py:186} INFO - Started process (PID=9325) to work on /opt/airflow/dags/A0265912B.py
[2025-03-16T13:22:46.976+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-16T13:22:46.978+0000] {logging_mixin.py:190} INFO - [2025-03-16T13:22:46.978+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-16T13:22:46.985+0000] {logging_mixin.py:190} INFO - [2025-03-16T13:22:46.982+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-16T13:22:46.985+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-16T13:22:46.998+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.025 seconds
[2025-03-16T14:21:34.170+0000] {processor.py:186} INFO - Started process (PID=9391) to work on /opt/airflow/dags/A0265912B.py
[2025-03-16T14:21:34.171+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-16T14:21:34.172+0000] {logging_mixin.py:190} INFO - [2025-03-16T14:21:34.172+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-16T14:21:34.177+0000] {logging_mixin.py:190} INFO - [2025-03-16T14:21:34.175+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-16T14:21:34.177+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-16T14:21:34.188+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.022 seconds
[2025-03-16T15:24:54.340+0000] {processor.py:186} INFO - Started process (PID=9457) to work on /opt/airflow/dags/A0265912B.py
[2025-03-16T15:24:54.341+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-16T15:24:54.343+0000] {logging_mixin.py:190} INFO - [2025-03-16T15:24:54.343+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-16T15:24:54.350+0000] {logging_mixin.py:190} INFO - [2025-03-16T15:24:54.349+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-16T15:24:54.350+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-16T15:24:54.362+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.024 seconds
[2025-03-16T15:28:41.235+0000] {processor.py:186} INFO - Started process (PID=9522) to work on /opt/airflow/dags/A0265912B.py
[2025-03-16T15:28:41.235+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-16T15:28:41.238+0000] {logging_mixin.py:190} INFO - [2025-03-16T15:28:41.237+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-16T15:28:41.247+0000] {logging_mixin.py:190} INFO - [2025-03-16T15:28:41.246+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-16T15:28:41.250+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-16T15:28:41.264+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.031 seconds
[2025-03-16T15:47:18.065+0000] {processor.py:186} INFO - Started process (PID=9588) to work on /opt/airflow/dags/A0265912B.py
[2025-03-16T15:47:18.066+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-16T15:47:18.067+0000] {logging_mixin.py:190} INFO - [2025-03-16T15:47:18.067+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-16T15:47:18.074+0000] {logging_mixin.py:190} INFO - [2025-03-16T15:47:18.072+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-16T15:47:18.074+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-16T15:47:18.087+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.026 seconds
[2025-03-16T16:34:21.157+0000] {processor.py:186} INFO - Started process (PID=9654) to work on /opt/airflow/dags/A0265912B.py
[2025-03-16T16:34:21.158+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-16T16:34:21.159+0000] {logging_mixin.py:190} INFO - [2025-03-16T16:34:21.159+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-16T16:34:21.168+0000] {logging_mixin.py:190} INFO - [2025-03-16T16:34:21.164+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-16T16:34:21.172+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-16T16:34:21.184+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.030 seconds
[2025-03-16T17:31:54.601+0000] {processor.py:186} INFO - Started process (PID=9719) to work on /opt/airflow/dags/A0265912B.py
[2025-03-16T17:31:54.602+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-16T17:31:54.603+0000] {logging_mixin.py:190} INFO - [2025-03-16T17:31:54.603+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-16T17:31:54.614+0000] {logging_mixin.py:190} INFO - [2025-03-16T17:31:54.611+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-16T17:31:54.614+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-16T17:31:54.627+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.030 seconds
[2025-03-16T19:10:47.135+0000] {processor.py:186} INFO - Started process (PID=9785) to work on /opt/airflow/dags/A0265912B.py
[2025-03-16T19:10:47.136+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-16T19:10:47.138+0000] {logging_mixin.py:190} INFO - [2025-03-16T19:10:47.138+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-16T19:10:47.147+0000] {logging_mixin.py:190} INFO - [2025-03-16T19:10:47.143+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-16T19:10:47.147+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-16T19:10:47.161+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.028 seconds
[2025-03-16T20:34:15.442+0000] {processor.py:186} INFO - Started process (PID=9851) to work on /opt/airflow/dags/A0265912B.py
[2025-03-16T20:34:15.446+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-16T20:34:15.449+0000] {logging_mixin.py:190} INFO - [2025-03-16T20:34:15.448+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-16T20:34:15.462+0000] {logging_mixin.py:190} INFO - [2025-03-16T20:34:15.461+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-16T20:34:15.463+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-16T20:34:15.479+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.043 seconds
[2025-03-16T22:12:55.400+0000] {processor.py:186} INFO - Started process (PID=9916) to work on /opt/airflow/dags/A0265912B.py
[2025-03-16T22:12:55.405+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-16T22:12:55.408+0000] {logging_mixin.py:190} INFO - [2025-03-16T22:12:55.407+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-16T22:12:55.413+0000] {logging_mixin.py:190} INFO - [2025-03-16T22:12:55.413+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-16T22:12:55.413+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-16T22:12:55.424+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.027 seconds
[2025-03-16T23:22:35.491+0000] {processor.py:186} INFO - Started process (PID=9981) to work on /opt/airflow/dags/A0265912B.py
[2025-03-16T23:22:35.492+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/A0265912B.py for tasks to queue
[2025-03-16T23:22:35.494+0000] {logging_mixin.py:190} INFO - [2025-03-16T23:22:35.494+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/A0265912B.py
[2025-03-16T23:22:35.501+0000] {logging_mixin.py:190} INFO - [2025-03-16T23:22:35.500+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/A0265912B.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/A0265912B.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2025-03-16T23:22:35.501+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/A0265912B.py
[2025-03-16T23:22:35.512+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/A0265912B.py took 0.023 seconds
